/**
 * Written descriptions of photographs, by path. `work-data.ts` is
 * regenerated by the harvest and carries none, so they live here and
 * `withAlt` in `lib/work.ts` lays them over it. A photograph not listed
 * keeps the generated "Project, frame 3 of 14".
 *
 * The booking pages' covers come first: the first photographs a visitor
 * from a search sees. What a picture shows, not
 * who is in it: no client is named unless the project already is.
 */
export const ALT: Record<string, string> = {
  // The homepage's cover and sessions
  "/work/aera-wraith/01.jpg": "Figure in a hood and bodysuit standing on a lit plinth in a smoky ruined chamber",
  "/work/azure-bloom/08.jpg": "Model with a natural afro in a tiered white tulle dress and a blue ruffled choker, on white",
  "/work/liminal/01.jpg": "Model with hair up in an oversized jacket, lit orange from behind with a teal edge light",
  "/work/wrapped-up/02.jpg": "Model in a black strapless top seen through stretched plastic wrap",
  "/work/fauxtopia/01.jpg": "Model in a fur-trimmed hooded coat on the shoreline at sunset",
  "/work/i-wanna-be-a-human/01.jpg": "Model in a sculptural black PVC and tulle look, flanked by motion-blurred figures",

  // Headshots
  "/work/headshots/01.jpg": "Studio headshot of a person with long dark wavy hair in a black top against a white background",
  "/work/headshots/02.jpg": "Studio headshot of a person with long highlighted hair in a black blazer against a white background",
  "/work/headshots/03.jpg": "Studio headshot of a person with dark hair pulled back, a gold name necklace and a black top, on white",
  "/work/headshots/04.jpg": "Headshot of a smiling person with dark wavy hair in a black t-shirt against a black background",
  "/work/headshots/05.jpg": "Headshot of a young person with short curly hair in a black t-shirt against a black background",
  "/work/headshots/06.jpg": "Headshot of a person with shoulder-length light brown hair and a pendant chain, on black",
  "/work/headshots/07.jpg": "Headshot of a person with a wide smile in a black v-neck t-shirt against a black background",
  "/work/headshots/08.jpg": "Headshot of a person with short dark hair in a black henley against a black background",
  "/work/headshots/10.jpg": "Headshot of a smiling person with blond hair in a black t-shirt against a black background",
  "/work/headshots/11.jpg": "Headshot of a young person with short dark hair and a cord necklace, on black",

  // Graduation
  "/work/graduation/01.jpg": "Graduate in a blue and gold stole on campus, palm trees and a low sun behind",
  "/work/graduation/02.jpg": "Graduate in a suit and blue and gold stole sitting on brick steps under a clear sky",
  "/work/graduation/03.jpg": "Graduate in cap and gown with a blue and gold stole in a glass campus walkway",
  "/work/graduation/04.jpg": "Graduate in sunglasses and a blue and gold stole in front of the San Jose State University sign",
  "/work/graduation/05.jpg": "Graduate in a black gown and gold stole sitting on sunlit stone steps",
  "/work/graduation/06.jpg": "Graduate in a gown and gold stole sitting on the steps of an ornate campus building",
  "/work/graduation/07.jpg": "Graduate in cap, gown and gold stole by tall windows in a wood-panelled room",
  "/work/graduation/08.jpg": "Graduate in a black dress and gold stole sitting on a library table by the windows",
  "/work/graduation/09.jpg": "Graduate with curly hair and a gold stole looking toward arched stained windows",
  "/work/graduation/10.jpg": "Graduate in a white dress and woven stole leaning on a rail beside a domed building",

  // Weddings
  "/work/weddings/01.jpg": "Bride and groom walking hand in hand down a marble corridor at San Francisco City Hall",
  "/work/weddings/02.jpg": "Bride and groom embracing, foreheads together, beside a carved stone column",
  "/work/weddings/03.jpg": "Bride and groom seen from behind, holding hands at the balustrade under an arched window",
  "/work/weddings/04.jpg": "Groom with an arm around the bride, holding a red bouquet, on the City Hall gallery",
  "/work/weddings/05.jpg": "Groom kissing the bride's temple as they sit in a lattice window with red roses",
  "/work/weddings/06.jpg": "Bride resting head on the groom's shoulder in the marble rotunda, bouquet in hand",
  "/work/weddings/07.jpg": "Bride sitting in a tall lattice window with the groom leaning in close",
  "/work/weddings/08.jpg": "Groom kissing the bride's cheek at the stone balustrade, red bouquet at the bride's side",
  "/work/weddings/09.jpg": "Bride and groom framed small in a lattice window on the marble gallery",
  "/work/weddings/10.jpg": "Bride and groom standing close under a dark arched window, looking at the camera",

  // Model digitals
  "/work/abril/03.jpg": "Model digital of a person with curly dark hair in a white henley, hand to the face, on a grey studio backdrop",
  "/work/giselle-studio-digitals/14.jpg": "Full-length model digital of a person in black underwear, standing straight on a white backdrop",
  "/work/mya/01.jpg": "Model digital of a person in a black bodysuit and boots sitting on a white studio floor",
  "/work/taneka/01.jpg": "Model digital of a person with blonde-streaked hair lying on a white studio floor",
  "/work/zoe/01.jpg": "Model digital of a person with long black hair in a black long-sleeve top on a white floor",

  // Portraits
  "/work/opal/01.jpg": "Studio portrait of a figure in white lingerie and white tights reclining on a grey backdrop",
  "/work/serif/01.jpg": "Studio portrait of a figure in a white shirt crouched low, looking over a knee",
  "/work/aether/01.jpg": "Portrait of a figure with long braids leaning over the back of a wooden chair, cool blue light",
  "/work/solitude/01.jpg": "Portrait of a figure in a sheer white shirt and black tights crouching in the studio",
  "/work/sonder/01.jpg": "Portrait of a figure sitting on the floor in a pool of hard light, dark studio around",

  // Music
  "/work/iris/07.jpg": "Musician in a leather jacket and platform boots sitting on a metal chair beside an old television",
  "/work/cyber1a/01.jpg": "Artist leaning on a CRT television in blue light, face on its screen",
  "/work/valgur/02.jpg": "Two musicians in armour standing in fog under a single shaft of light",
  "/work/torteline/05.jpg": "Producer sitting on the floor in teal light behind a synthesizer and a MIDI keyboard",
  "/work/l3na/01.jpg": "Artist in white sitting on the floor in deep blue light, one arm raised",
  "/work/sage/11.jpg": "Artist lying on the studio floor in a blue dress and white boots beside a CRT television",
  "/work/sara/08.jpg": "Artist in black sitting on a chair in purple light and haze",

  // Brand campaigns
  "/work/paradox/01.jpg": "A barber with tattooed arms combing a model's hair backstage at Educo Academy HairJam",
  "/work/ukiyosunknown/01.jpg": "Model in black leather crouching beside a television on a white studio floor",
  "/work/sago/01.jpg": "Figure in a SAGO varsity jacket and sunglasses standing in tall golden grass at sunset",
  "/work/goodcult/01.jpg": "Two models in matching Goodcult graphic hoodies against a teal wall, one seated on the floor",
  "/work/sols/01.jpg": "Model with teal hair and a bandana sitting on a rooftop in a bikini top and denim",
  "/work/jubo/03.jpg": "Figure in an orange beanie and green graphic tee beneath a steel pylon",
  "/work/hua/16.jpg": "Figure in a hooded coat with rabbit ears standing in a red-lit graffiti tunnel",
  "/work/diesel/03.jpg": "Close-up of a model's Diesel waistband and low-slung jeans, a group lounging in a warehouse behind",
  "/work/wired-magazine/01.jpg": "Skateboarder in wide jeans mid-push along a grey wall, shot from the ground",
  "/work/nabu/59.jpg": "Figure with long curly hair in a black NABU shirt on a rooftop under a dusk sky",
};
