/* Generated by `scripts/make-clients.mjs` from `public/clients/*.svg`.
 * Do not edit: add or replace an SVG and run the script.
 *
 * Every colour is `currentColor`, so a mark sits muted in the row, comes up
 * to full contrast on hover, and works on either theme. See the script for
 * why these are inlined rather than served as files.
 */

/** One client's mark, ready to drop into an `<svg>`. */
export type ClientMark = { viewBox: string; body: string };

/** By slug — the same slug the project has. Empty until a logo is added. */
export const CLIENT_MARKS: Record<string, ClientMark> = {

};
