/**
 * The one way the app reads the archive.
 *
 * `work-data.ts` is generated by `scripts/harvest.mjs` and gets overwritten;
 * this file is hand-written and stable, so every page imports from here. It
 * also holds the editorial decisions the raw data cannot make — what is
 * featured, what leads the homepage, and how the old site's three nav groups
 * collapse into the new two.
 */
import { PROJECTS as HARVESTED, CATEGORIES } from "./work-data";
import type { Project, Category, Frame } from "./work-types";
import { COVER_RELEASES } from "./cover-art-data";

export type { Project, Category, Frame };
export { CATEGORIES, COVER_RELEASES };

/**
 * The cover-art gallery, with the harvest's pictures replaced by Julian's own
 * masters (`scripts/cover-art.mjs`).
 *
 * Same reason the homepage cover is overridden: the harvested copies are the
 * old site's 1600px re-compressions, with the release titles buried in alt
 * text and zero-width spaces baked into them, where the masters run to
 * 7952px and are correctly named. The delivered set also holds a release the
 * old site never published.
 *
 * Substituted into `PROJECTS` rather than exported alongside it, so the work
 * index, the route, the lightbox and the discipline list cannot end up
 * showing two different versions of the same gallery.
 */
const withCoverArt = (project: Project): Project => {
  const images = COVER_RELEASES.flatMap((r) => r.frames);
  if (!images.length) return project;

  return {
    ...project,
    // "COVERART" was one word on the old site and reads as a typo set large —
    // on the project page it is printed as the category too, so both go.
    name: "Cover art",
    categories: project.categories.map((c) =>
      c.slug === "coverart" ? { ...c, name: "Cover art" } : c,
    ),
    cover: { ...images[0], src: "/covers/cover.jpg", width: 600, height: 600 },
    images,
  };
};

export const PROJECTS: Project[] = HARVESTED.map((p) =>
  p.slug === "coverart" ? withCoverArt(p) : p,
);

/**
 * The old nav split commissioned work across WORK and MUSIC, which asked a
 * visitor to know in advance whether a cover-art job files under "music" or
 * "work". Both are commissions, judged by the same people, so they merge.
 *
 * SESSIONS stays separate — a graduation client and an art director want
 * different things from the first screen (price and dates vs. clients and
 * credits), and that is the one split worth keeping.
 */
const inSessions = (p: Project) => p.categories.some((c) => c.section === "SESSIONS");

/** Commissioned work: editorial, campaigns, portraits, music, film. */
export const COMMISSIONS: Project[] = PROJECTS.filter(
  (p) => p.categories.length > 0 && !inSessions(p),
);

/** Client-session work: graduation, headshots, weddings, studio digitals. */
export const SESSIONS: Project[] = PROJECTS.filter(inSessions);

/**
 * Projects the old site published but never linked from its nav — older work,
 * tests, one-offs. They keep working as routes so nothing already linked or
 * indexed breaks, but they stay out of the indexes until Julian files one
 * under a category by hand.
 */
export const UNFILED: Project[] = PROJECTS.filter((p) => p.categories.length === 0);

export const WORK_CATEGORIES: Category[] = CATEGORIES.filter((c) => c.section !== "SESSIONS");
export const SESSION_CATEGORIES: Category[] = CATEGORIES.filter((c) => c.section === "SESSIONS");

const bySlug = new Map(PROJECTS.map((p) => [p.slug, p]));

export const getProject = (slug: string): Project | undefined => bySlug.get(slug);

export const projectsIn = (categorySlug: string): Project[] =>
  PROJECTS.filter((p) => p.categories.some((c) => c.slug === categorySlug));

/**
 * Whether a nav leaf is one gallery rather than a listing of projects.
 *
 * The old nav mixed the two without saying so: EDITORIAL is eighteen separate
 * projects, where COVERART and WEDDINGS are each a single gallery published
 * under the category's own slug.
 */
const isOwnGallery = (categorySlug: string): boolean => {
  const inCategory = projectsIn(categorySlug);
  return inCategory.length === 1 && inCategory[0].slug === categorySlug;
};

/** Display names, where the old site's nav label does not read well. */
const CATEGORY_LABELS: Record<string, string> = {
  // One word on the old site, and it looks like a typo set large.
  coverart: "Cover art",
};

/**
 * A category's name as a heading.
 *
 * The old nav set every label in caps, which is a styling decision baked into
 * the content: sentence case is what a page heading needs, and the `label`
 * class puts the caps back where the design wants them.
 */
export const categoryLabel = (category: Category): string =>
  CATEGORY_LABELS[category.slug] ??
  category.name.charAt(0) + category.name.slice(1).toLowerCase();

/**
 * Where a category's work lives.
 *
 * A listing gets its own filtered index page — a real URL, so a discipline
 * can be linked, shared and indexed, rather than a filter someone has to
 * apply by hand after landing on everything at once.
 *
 * A category that is itself one gallery points at the gallery: the listing
 * for it would be a page with a single row on it, which is a click for
 * nothing. And a category with no work yet has no page to point at, so it
 * falls back to the full index instead of a route that does not exist.
 */
export const categoryHref = (categorySlug: string): string => {
  const inCategory = projectsIn(categorySlug);
  if (inCategory.length === 0) return "/work";
  if (isOwnGallery(categorySlug)) return `/work/${categorySlug}`;
  return `/work/category/${categorySlug}`;
};

/** A category as the index renders it: name plus where it goes. */
export type CategoryLink = { slug: string; name: string; href: string };

/**
 * The category row on the work index, resolved.
 *
 * Prepared here rather than passed as a `categoryHref` function, because the
 * index is a client component and a server component cannot hand a function
 * across that boundary — the href each category needs is data, so it travels
 * as data.
 */
export const WORK_CATEGORY_LINKS: CategoryLink[] = WORK_CATEGORIES.filter(
  // VIDEO and MUSIC VIDEO are in the old nav with nothing behind them — the
  // work is on Vimeo and was never published here. A row that navigates
  // nowhere is worse than one that is absent, so they wait until there is
  // something to open.
  (c) => projectsIn(c.slug).length > 0,
).map((c) => ({
  slug: c.slug,
  // Through `categoryLabel`, so "COVERART" reads as "COVER ART" once the
  // `label` class puts the caps back.
  name: categoryLabel(c),
  href: categoryHref(c.slug),
}));

/**
 * The frame a project is represented by elsewhere on the site — the small
 * derivative of its opening image.
 *
 * The opener, because Julian already sequences his galleries and the first
 * frame is a deliberate choice; second-guessing it with "the widest" or "the
 * darkest" would override an edit he already made.
 */
export const coverOf = (p: Project): Frame => p.cover;

/**
 * Homepage order. Named explicitly rather than derived, because "what leads"
 * is the most editorial decision on the site and it should be one obvious
 * line to change.
 *
 * WIRED first: it is the strongest credential, and the thing a new visitor
 * should see before anything else.
 */
export const FEATURED_SLUGS = [
  "wired-magazine",
  "oakley-x-nike",
  "luxe-meets-future",
  "dystopia",
  "ukiyosunknown",
  "sago",
] as const;

export const FEATURED: Project[] = FEATURED_SLUGS.map((s) => bySlug.get(s)).filter(
  (p): p is Project => Boolean(p),
);

/**
 * The press strip on the homepage. The old site buried these as plain text at
 * the bottom of /about; they are the reason an art director keeps reading, so
 * they move up and each links into the work it refers to.
 */
export const PRESS = [
  { name: "WIRED", slug: "wired-magazine" },
  { name: "Oakley x Nike", slug: "oakley-x-nike" },
  { name: "UKIYOSUNKNOWN", slug: "ukiyosunknown" },
  { name: "JUBO", slug: "jubo" },
  { name: "SAGO", slug: "sago" },
].filter((p) => bySlug.has(p.slug));

/**
 * The homepage cover.
 *
 * One frame, static. A single photograph is the oldest and least dateable way
 * to open a portfolio, and it is the fastest — one image to decode, which is
 * what a visitor's patience is actually spent on.
 *
 * Named here rather than derived, because this is the most consequential
 * editorial decision on the site: it is the first thing anyone sees. Change
 * the slug to change the cover.
 *
 * The full-size frame, not the small cover derivative — this one runs the
 * full height of the page on a large display.
 */
export const COVER_SLUG = "wired-magazine";

export const HERO: { project: Project; frame: Frame } | null = (() => {
  const project = bySlug.get(COVER_SLUG) ?? FEATURED[0] ?? COMMISSIONS[0];
  // Prefer a portrait frame. The cover sits in a half-width, full-height
  // column, and `object-cover` on a landscape frame in that shape crops away
  // both sides — usually most of the subject.
  const frame = project?.images.find((f) => f.height > f.width) ?? project?.images[0];
  return project && frame ? { project, frame } : null;
})();

/**
 * Which contact-form branch a project should pre-select.
 *
 * The point is that someone who has just looked at a campaign and wants one
 * arrives at the form with "Campaign" already chosen and the usage-rights
 * question already asked. Every question they do not have to answer from a
 * cold start is a chance they do not abandon the form.
 */
export const enquiryTypeFor = (p: Project): string => {
  const slugs = p.categories.map((c) => c.slug);

  if (slugs.some((s) => ["artist-presskit", "music-video", "coverart", "events"].includes(s)))
    return "music";
  if (slugs.includes("campaigns")) return "campaign";
  if (slugs.includes("editorial")) return "editorial";
  if (p.categories.some((c) => c.section === "SESSIONS")) return "session";
  return "other";
};

/**
 * The project after this one, for the end of a case study.
 *
 * A project page that ends in a footer is a dead end, and a dead end is an
 * exit. Wrapping round at the end means there is always a next thing.
 */
export const nextAfter = (p: Project): Project | undefined => {
  const pool = p.categories.some((c) => c.section === "SESSIONS") ? SESSIONS : COMMISSIONS;
  const i = pool.findIndex((x) => x.slug === p.slug);
  if (i === -1) return pool[0];
  return pool[(i + 1) % pool.length];
};

/**
 * The disciplines the homepage cycles through, each with a frame to show for
 * it.
 *
 * This is what the cover is *for*: "photographer" is a job title, whereas
 * editorial, campaigns, portraits and music are the four things somebody
 * might actually be here to commission. Switching between them says the range
 * in the first few seconds, which one static cover cannot.
 *
 * Built from the nav's own category order rather than a hand-written list, so
 * it cannot drift out of step with the work. Each one takes its frame from the
 * first project filed under it — Julian's own ordering, so the lead project is
 * already his pick — preferring a portrait frame, because the cover sits in a
 * tall column and `object-cover` on a landscape frame there crops away both
 * sides.
 */
export type Discipline = {
  slug: string;
  name: string;
  /** How many projects are filed under it, for the index. */
  count: number;
  /** Where the row goes when clicked. */
  href: string;
  project: Project;
  frame: Frame;
};

/**
 * Hand-picked cover frames, overriding the one derived from the archive.
 *
 * These live in `public/hero/` rather than in `public/work/`, because they are
 * chosen to be a cover — a specific frame Julian wants leading the site —
 * rather than being part of a project's sequence. That also keeps them clear
 * of `scripts/harvest.mjs`, which owns everything under `public/work/`.
 *
 * `color` is the mat drawn behind the picture where the column is wider or
 * taller than the frame. It is the image's mean, not its dominant: on a
 * sunset frame the dominant bucket comes back near-black, which reads as a
 * letterbox bar instead of a mount.
 *
 * Add a full-resolution original to `PICS/`, then process it the same way the
 * archive is processed — 1600px wide, mozjpeg q82 — and add an entry here.
 */
const COVER_OVERRIDES: Record<string, Frame> = {
  portraits: {
    src: "/hero/cover.jpg",
    width: 1600,
    height: 2133,
    color: "#897A74",
    alt: "Model in a fur-trimmed hooded coat on the shoreline at sunset",
  },
};

/**
 * The disciplines the cover cycles through, in order.
 *
 * Named explicitly rather than taken as the first N categories. The nav order
 * puts `video` fifth, but cover art is the more representative fifth thing he
 * does — and which five lead the site is an editorial call, not something to
 * be decided by a `slice`.
 */
const DISCIPLINE_SLUGS = ["editorial", "campaigns", "portraits", "mixed-media", "coverart"];


/**
 * Where the unit of work is not a frame.
 *
 * Cover art is counted in releases: two of them are sleeves with a front and
 * a back, and counting those as two covers each both overstates the work and
 * disagrees with the number the section's own link shows.
 */
const DISCIPLINE_COUNTS: Record<string, number> = {
  coverart: COVER_RELEASES.length,
};

export const DISCIPLINES: Discipline[] = DISCIPLINE_SLUGS.map(
  (slug) => CATEGORIES.find((c) => c.slug === slug),
)
  .filter((c): c is Category => Boolean(c))
  .map((category) => {
    const inCategory = projectsIn(category.slug);
    const project = inCategory[0];
    if (!project) return null;

    const frame =
      COVER_OVERRIDES[category.slug] ??
      project.images.find((f) => f.height > f.width) ??
      project.images[0];
    if (!frame) return null;

    // Some nav leaves are a listing of many projects (EDITORIAL); others are
    // themselves a single gallery (COVERART, WEDDINGS). Counting projects for
    // the second kind always reports "1", which is true and useless — the
    // number a visitor wants is how much work is in there.
    const count =
      DISCIPLINE_COUNTS[category.slug] ??
      (isOwnGallery(category.slug) ? project.images.length : inCategory.length);

    return {
      slug: category.slug,
      name: categoryLabel(category),
      count,
      href: categoryHref(category.slug),
      project,
      frame,
    };
  })
  .filter((d): d is Discipline => d !== null);

/**
 * The cover-art work.
 *
 * It sits apart from the rest of the archive because its format does: every
 * frame is exactly 1:1, because that is what a release needs. Shown in a
 * square grid rather than folded into the portrait-shaped selected-work grid,
 * where squares would have to be cropped to fit.
 */
export const COVER_ART: Project | undefined = getProject("coverart");
