/**
 * The one way the app reads the archive.
 *
 * `work-data.ts` is generated by `scripts/harvest.mjs` and gets overwritten;
 * this file is hand-written and stable, so every page imports from here. It
 * also holds the editorial decisions the raw data cannot make — what is
 * featured, what leads the homepage, and how the old site's three nav groups
 * collapse into the new two.
 */
import {
  PROJECTS as HARVESTED,
  CATEGORIES as HARVESTED_CATEGORIES,
} from "./work-data";
import type { Project, Category, Frame, TextBlock } from "./work-types";
import { COVER_RELEASES } from "./cover-art-data";
import { CONTENT } from "./content";
import {
  ADDED,
  HIDDEN,
  RECATEGORISED,
  REFRAMED,
  RECREDITED,
  ORDER,
  DISCIPLINE_COVERS,
  ADDED_DISCIPLINES,
  isTextRef,
  type AddedProject,
} from "./added";

export type { Project, Category, Frame, TextBlock };
/**
 * Every discipline: the ones the old nav had, plus any added in /admin.
 *
 * Appended rather than merged in place, so the harvested order — which is the
 * old site's nav order and what the work index reads — is untouched. A slug
 * that already exists is dropped: `content/projects.json` is edited through a
 * browser form, and a duplicate there should cost the new entry rather than
 * put two rows with one slug into every index on the site.
 *
 * Declared here, above the consts that read it, rather than left as the
 * re-export it used to be.
 */
export const CATEGORIES: Category[] = [
  ...HARVESTED_CATEGORIES,
  ...ADDED_DISCIPLINES.filter(
    (d) => !HARVESTED_CATEGORIES.some((c) => c.slug === d.slug),
  ),
];

export { COVER_RELEASES };

/**
 * The cover-art gallery, with the harvest's pictures replaced by Julian's own
 * masters (`scripts/cover-art.mjs`).
 *
 * Same reason the homepage cover is overridden: the harvested copies are the
 * old site's 1600px re-compressions, with the release titles buried in alt
 * text and zero-width spaces baked into them, where the masters run to
 * 7952px and are correctly named. The delivered set also holds a release the
 * old site never published.
 *
 * Substituted into `PROJECTS` rather than exported alongside it, so the work
 * index, the route, the lightbox and the discipline list cannot end up
 * showing two different versions of the same gallery.
 */
const withCoverArt = (project: Project): Project => {
  const images = COVER_RELEASES.flatMap((r) => r.frames);
  if (!images.length) return project;

  return {
    ...project,
    // "COVERART" was one word on the old site and reads as a typo set large —
    // on the project page it is printed as the category too, so both go.
    name: "Cover art",
    // The category used to be renamed here too. `relabel` does it now, for
    // this category and every other one, from `CATEGORY_LABELS`.
    cover: { ...images[0], src: "/covers/cover.jpg", width: 600, height: 600 },
    images,
  };
};

/** The width `scripts/harvest.mjs` cuts every cover derivative to. */
const COVER_WIDTH = 600;

/**
 * Projects whose opener is not the frame the archive happens to lead with.
 *
 * The archive's order is the old site's order, and in a few places the frame
 * that should introduce a project is not the one sitting first in it. Naming
 * the frame here moves it to the front of the gallery *and* makes it the
 * cover, because those are the same decision — `coverOf` exists on the
 * premise that the cover is the opener, and a project whose card shows one
 * photograph and whose page opens on another reads as a mistake.
 *
 * The derivative lives in `public/hero/` rather than beside the frame it came
 * from. `harvest.mjs` owns `public/work/` and rebuilds `cover.jpg` from
 * whatever is first in the archive whenever it is missing — so a cover put
 * there would survive today and quietly revert to the wrong photograph on the
 * next clean harvest.
 */
const LEAD_FRAMES: Record<string, string> = {
  // Julian's pick: the second frame, not the first.
  "luxe-meets-future": "/work/luxe-meets-future/02.jpg",
};

const withLeadFrame = (project: Project): Project => {
  const wanted = LEAD_FRAMES[project.slug];
  const lead = wanted
    ? project.images.find((f) => f.src === wanted)
    : undefined;
  // Silently unchanged if the named frame is gone, rather than throwing a
  // build that is otherwise fine — a re-harvest can renumber a gallery.
  if (!lead) return project;

  return {
    ...project,
    images: [lead, ...project.images.filter((f) => f.src !== lead.src)],
    cover: {
      ...lead,
      src: `/hero/${project.slug}.jpg`,
      width: COVER_WIDTH,
      height: Math.round((COVER_WIDTH / lead.width) * lead.height),
    },
  };
};

/**
 * A project added through `/admin`, in the shape the rest of the site reads.
 *
 * The editor stores one category slug; everything downstream wants the whole
 * `Category`, so it is looked up here against the manifest rather than being
 * duplicated into the JSON where it could drift.
 *
 * An unknown slug throws. The alternative — filing the project under nothing —
 * would put it in the archive but in no index, which is the kind of failure
 * somebody only finds weeks later while wondering where a shoot went.
 */
const fromAdded = (p: AddedProject): Project => {
  const category = CATEGORIES.find((c) => c.slug === p.categorySlug);
  if (!category) {
    throw new Error(
      `content/projects.json: "${p.slug}" is filed under "${p.categorySlug}", which is not a category.`,
    );
  }

  return {
    slug: p.slug,
    name: p.name,
    headline: null,
    intent: null,
    credits: p.credits,
    categories: [category],
    cover: p.cover,
    images: p.images,
  };
};

/**
 * Every project, added work first — and including what is hidden.
 *
 * `projectsIn()` takes the first project in a category as that category's
 * lead — the frame its row shows, and what the discipline page opens with —
 * so putting new work at the front means a shoot added today is what the site
 * leads with, rather than sinking beneath a migration ordered by the old
 * site. The hand-picked cover overrides still win where they exist.
 *
 * Exported unfiltered for `/admin` only: the editor has to be able to show a
 * hidden project in order to offer to bring it back, which is the one context
 * where the filter below is wrong.
 */
/**
 * Refiles a project under the discipline `/admin` chose for it.
 *
 * Applied after the merge so it reaches harvested projects as well as added
 * ones — their categories come from the generated manifest, where an edit
 * would survive only until the next harvest.
 *
 * An unknown category slug is left alone rather than throwing. This map is
 * keyed by project slug, and a re-harvest can retire a project entirely; a
 * stale key should not be able to fail a build that is otherwise fine.
 */
const refile = (project: Project): Project => {
  const wanted = RECATEGORISED[project.slug];
  if (!wanted) return project;

  const category = CATEGORIES.find((c) => c.slug === wanted);
  if (!category) return project;

  return { ...project, categories: [category] };
};

/**
 * Replaces the credits `/admin` has rewritten.
 *
 * A map for the same reason `refile` uses one: the harvested projects keep
 * their credits in the generated manifest, and `scripts/harvest.mjs` would
 * take an edit there back on its next run.
 *
 * Checked with `in` rather than by truthiness, so an empty array is honoured.
 * "This project's harvested credits are wrong, publish none" is a real
 * instruction and the only way to say it.
 */
const recredit = (project: Project): Project =>
  project.slug in RECREDITED
    ? { ...project, credits: RECREDITED[project.slug] }
    : project;

/**
 * Re-sequences a gallery that `/admin` has reordered, trimmed or added to.
 *
 * Applied last, after the merge and after the lead-frame and cover-art
 * substitutions, because it is the most specific decision available: somebody
 * looked at this gallery and said what it should be.
 *
 * Most entries are bare paths, and the frame they name is looked up in the
 * archive so its dimensions and mat colour stay whatever the last harvest
 * made them. A path that is no longer there is dropped rather than throwing —
 * a re-harvest can renumber a gallery, and a stale entry should cost a frame
 * and not the build. If that leaves nothing at all the override is ignored
 * entirely, because a project rendering as a title over nothing is worse than
 * one rendering in its original order.
 *
 * A whole `Frame` is a photograph added through the editor: it exists nowhere
 * else, so its own numbers are the only ones there are.
 */
const reframe = (project: Project): Project => {
  const wanted = REFRAMED[project.slug];
  if (!wanted?.length) return project;

  const archive = new Map(project.images.map((f) => [f.src, f]));

  /* One pass, two outputs. The stored sequence interleaves photographs and
     writing; the site wants them apart — `images` feeds the gallery, the
     lightbox, the counts and the image sitemap, none of which have any use
     for a paragraph — so a block's position is recorded as the number of
     frames ahead of it and the lists part company here.

     Counted against surviving frames rather than against the stored list, so
     a frame dropped by a re-harvest pulls the writing after it up with it
     instead of leaving a block stranded past the end of the gallery. */
  const images: Frame[] = [];
  const blocks: TextBlock[] = [];

  for (const ref of wanted) {
    if (isTextRef(ref)) {
      blocks.push({
        heading: ref.heading,
        body: ref.body,
        after: images.length,
      });
      continue;
    }
    const found =
      typeof ref === "string"
        ? (archive.get(ref) ?? null)
        : (archive.get(ref.src) ?? ref);
    if (found) images.push(found);
  }

  if (!images.length) return project;

  return {
    ...project,
    images,
    blocks,
    // The cover is the opener — `coverOf` is built on that — so a gallery that
    // now opens on a different photograph gets a card showing it. The full
    // frame rather than the 600px derivative, because the derivative was cut
    // from the frame that used to lead and still shows it.
    cover: images[0].src === project.images[0]?.src ? project.cover : images[0],
  };
};

/* Moved above the pipeline below, which now calls it. A `const` arrow is not
   hoisted, so `ALL_PROJECTS` evaluating at module load would reach into the
   temporal dead zone and throw on import. */
/** Display names, where the old site's nav label does not read well. */
const CATEGORY_LABELS: Record<string, string> = {
  // One word on the old site, and it looks like a typo set large.
  coverart: "Cover art",
  // "Campaigns" alone is ambiguous next to EDITORIAL — it could as easily mean
  // a political or fundraising one. The client is a brand, and saying so is
  // what an art director is scanning the index for.
  campaigns: "Brand campaigns",
};

/**
 * A category's name as a heading.
 *
 * The old nav set every label in caps, which is a styling decision baked into
 * the content: sentence case is what a page heading needs, and the `label`
 * class puts the caps back where the design wants them.
 */
export const categoryLabel = (category: Category): string =>
  CATEGORY_LABELS[category.slug] ??
  category.name.charAt(0) + category.name.slice(1).toLowerCase();

/**
 * Prints every category under its display name, once, for good.
 *
 * The labels above were only being applied where somebody remembered to call
 * `categoryLabel` — the cover index, the nav, a page heading. Everywhere that
 * printed `project.categories[0].name` got the raw manifest name instead, so
 * `/work` listed "CAMPAIGNS" while the nav above it said "Brand campaigns",
 * and the homepage tiles did the same. That was true before this function
 * existed and would have been true of every future rename.
 *
 * Fixed at the one place every consumer reads from rather than at each render
 * site, because the render sites are the part that keeps growing. `withCoverArt`
 * has been doing exactly this for `coverart` alone since the rebuild; this is
 * that, generalised.
 *
 * After `refile`, so a project moved to another discipline in /admin is
 * labelled by where it now is and not where it was.
 */
const relabel = (project: Project): Project => ({
  ...project,
  categories: project.categories.map((c) => ({ ...c, name: categoryLabel(c) })),
});

/**
 * The running order of the work, as dragged in /admin.
 *
 * `ORDER` is partial — it names only what has been moved. Anything absent
 * sorts after everything named, keeping the order the manifest gave it, so an
 * empty list is the site as harvested and moving one project to the front
 * costs one entry rather than a snapshot of all seventy-three.
 *
 * `Infinity` for the unnamed rather than a large number: it has to be greater
 * than every real index without anybody having to know how many there are.
 * Ties return 0, and `Array.prototype.sort` has been stable since ES2019, so
 * the unnamed keep their relative order instead of being shuffled.
 */
const rank = new Map(ORDER.map((slug, i) => [slug, i]));

const byRunningOrder = (a: Project, b: Project): number =>
  (rank.get(a.slug) ?? Infinity) - (rank.get(b.slug) ?? Infinity);

export const ALL_PROJECTS: Project[] = [
  ...ADDED.map(fromAdded),
  ...HARVESTED.map((p) =>
    p.slug === "coverart" ? withCoverArt(p) : withLeadFrame(p),
  ),
]
  .map((p) => relabel(reframe(recredit(refile(p)))))
  .sort(byRunningOrder);

/**
 * Filtered here, at the one place every consumer reads from, rather than at
 * each index. A hidden project has to be absent from the work index, the
 * discipline pages, the homepage band, `generateStaticParams`, the sitemap
 * and the old-URL redirects — and a list that has to be remembered in six
 * places is a list that will be forgotten in one.
 */
export const PROJECTS: Project[] = ALL_PROJECTS.filter(
  (p) => !HIDDEN.has(p.slug),
);

export { HIDDEN };

/**
 * The old nav split commissioned work across WORK and MUSIC, which asked a
 * visitor to know in advance whether a cover-art job files under "music" or
 * "work". Both are commissions, judged by the same people, so they merge.
 *
 * SESSIONS stays separate — a graduation client and an art director want
 * different things from the first screen (price and dates vs. clients and
 * credits), and that is the one split worth keeping.
 */
const inSessions = (p: Project) =>
  p.categories.some((c) => c.section === "SESSIONS");

export const projectsIn = (categorySlug: string): Project[] =>
  PROJECTS.filter((p) => p.categories.some((c) => c.slug === categorySlug));

/**
 * Whether a nav leaf is one gallery rather than a listing of projects.
 *
 * The old nav mixed the two without saying so: EDITORIAL is eighteen separate
 * projects, where COVERART and WEDDINGS are each a single gallery published
 * under the category's own slug.
 *
 * Moved up here from below `COMMISSIONS`, which now needs it. A `const` arrow
 * is not hoisted, so the definition has to precede the first use or the
 * module throws on import.
 */
const isOwnGallery = (categorySlug: string): boolean => {
  const inCategory = projectsIn(categorySlug);
  return inCategory.length === 1 && inCategory[0].slug === categorySlug;
};

/**
 * Whether a project *is* a discipline rather than a piece of work in one.
 *
 * Cover art, Automotive, Places and Event coverage are published as a single
 * gallery under the discipline's own slug — twenty-four record sleeves in one
 * page, a folder of cars — because there are no separate commissions behind
 * them to list. They are the discipline, drawn as a gallery.
 */
const isDiscipline = (p: Project) =>
  p.categories.some((c) => c.slug === p.slug && isOwnGallery(c.slug));

/**
 * Commissioned work: editorial, campaigns, portraits, music, film.
 *
 * Projects, and only projects. The four disciplines that are themselves one
 * gallery used to sit in here as a card apiece, so the index that says "59
 * commissioned projects" counted Cover art as one project and Editorial as
 * twenty-eight — and a grid of individual commissions had four whole
 * disciplines shuffled in among them, sorted by nothing a visitor could see.
 *
 * They keep their chip at the top of the index, which is where Julian wants
 * them and where they already went somewhere sensible: `categoryHref` sends a
 * one-gallery discipline straight to its gallery rather than to a listing
 * page with a single row on it.
 */
export const COMMISSIONS: Project[] = PROJECTS.filter(
  (p) => p.categories.length > 0 && !inSessions(p) && !isDiscipline(p),
);

/** Client-session work: graduation, headshots, weddings, studio digitals. */
export const SESSIONS: Project[] = PROJECTS.filter(inSessions);

/**
 * Projects the old site published but never linked from its nav — older work,
 * tests, one-offs. They keep working as routes so nothing already linked or
 * indexed breaks, but they stay out of the indexes until Julian files one
 * under a category by hand.
 */
export const UNFILED: Project[] = PROJECTS.filter(
  (p) => p.categories.length === 0,
);

export const WORK_CATEGORIES: Category[] = CATEGORIES.filter(
  (c) => c.section !== "SESSIONS",
);
export const SESSION_CATEGORIES: Category[] = CATEGORIES.filter(
  (c) => c.section === "SESSIONS",
);

const bySlug = new Map(PROJECTS.map((p) => [p.slug, p]));

export const getProject = (slug: string): Project | undefined =>
  bySlug.get(slug);

/**
 * Whether the Video discipline has anything behind it.
 *
 * Video is the one discipline whose work is not projects in the archive —
 * it is embeds, held in `content/site.json` and edited in /admin, because a
 * film lives on the client's channel and what this site owns is the poster
 * and the arrangement. So "does it have work" is a different question for
 * this one row, and this is it.
 */
const HAS_VIDEOS = CONTENT.videos.length > 0;

/**
 * Where a category's work lives.
 *
 * A listing gets its own filtered index page — a real URL, so a discipline
 * can be linked, shared and indexed, rather than a filter someone has to
 * apply by hand after landing on everything at once.
 *
 * A category that is itself one gallery points at the gallery: the listing
 * for it would be a page with a single row on it, which is a click for
 * nothing. And a category with no work yet has no page to point at, so it
 * falls back to the full index instead of a route that does not exist.
 */
export const categoryHref = (categorySlug: string): string => {
  // Video's page is the work rather than a listing of it, like `/work/coverart`
  // — and unlike every other discipline, what fills it is not in the archive.
  if (categorySlug === "video") return "/work/video";

  const inCategory = projectsIn(categorySlug);
  if (inCategory.length === 0) return "/work";
  if (isOwnGallery(categorySlug)) return `/work/${categorySlug}`;
  return `/work/category/${categorySlug}`;
};

/** A category as the index renders it: name plus where it goes. */
export type CategoryLink = { slug: string; name: string; href: string };

/**
 * The category row on the work index, resolved.
 *
 * Prepared here rather than passed as a `categoryHref` function, because the
 * index is a client component and a server component cannot hand a function
 * across that boundary — the href each category needs is data, so it travels
 * as data.
 */
export const WORK_CATEGORY_LINKS: CategoryLink[] = WORK_CATEGORIES.filter(
  /* A row that navigates nowhere is worse than one that is absent, so a
     discipline waits until there is something to open.

     Which was all of VIDEO and MUSIC VIDEO until now: both were in the old
     nav with nothing behind them. Video has a page as soon as one link is
     pasted into /admin — its work is embeds, not projects, so it is asked a
     different question. Music video is not a row at all any more: it is a
     section *inside* that page, which is how Julian asked for it and how six
     films read better than two thin pages. */
  (c) =>
    c.slug === "video"
      ? HAS_VIDEOS
      : c.slug !== "music-video" && projectsIn(c.slug).length > 0,
).map((c) => ({
  slug: c.slug,
  // Through `categoryLabel`, so "COVERART" reads as "COVER ART" once the
  // `label` class puts the caps back.
  name: categoryLabel(c),
  href: categoryHref(c.slug),
}));

/**
 * The frame a project is represented by elsewhere on the site — the small
 * derivative of its opening image.
 *
 * The opener, because Julian already sequences his galleries and the first
 * frame is a deliberate choice; second-guessing it with "the widest" or "the
 * darkest" would override an edit he already made.
 */
export const coverOf = (p: Project): Frame => p.cover;

/**
 * Homepage order. Named explicitly rather than derived, because "what leads"
 * is the most editorial decision on the site — which is also why it is in
 * `content/site.json` and editable in `/admin` rather than in this file.
 *
 * WIRED first: it is the strongest credential, and the thing a new visitor
 * should see before anything else.
 *
 * A slug that does not match a project is dropped rather than rendered as a
 * hole, so a typo in the editor costs a card and not the section.
 */
export const FEATURED_SLUGS: string[] = CONTENT.featured;

export const FEATURED: Project[] = FEATURED_SLUGS.map((s) =>
  bySlug.get(s),
).filter((p): p is Project => Boolean(p));

/**
 * The press strip on the homepage. The old site buried these as plain text at
 * the bottom of /about; they are the reason an art director keeps reading, so
 * they move up and each links into the work it refers to.
 */
export const PRESS = [
  { name: "WIRED", slug: "wired-magazine" },
  { name: "Oakley x Nike", slug: "oakley-x-nike" },
  { name: "UKIYOSUNKNOWN", slug: "ukiyosunknown" },
  { name: "JUBO", slug: "jubo" },
  { name: "SAGO", slug: "sago" },
].filter((p) => bySlug.has(p.slug));

/**
 * The homepage cover.
 *
 * One frame, static. A single photograph is the oldest and least dateable way
 * to open a portfolio, and it is the fastest — one image to decode, which is
 * what a visitor's patience is actually spent on.
 *
 * Named here rather than derived, because this is the most consequential
 * editorial decision on the site: it is the first thing anyone sees. Change
 * the slug to change the cover.
 *
 * The full-size frame, not the small cover derivative — this one runs the
 * full height of the page on a large display.
 */
export const COVER_SLUG: string = CONTENT.coverSlug;

export const HERO: { project: Project; frame: Frame } | null = (() => {
  const project = bySlug.get(COVER_SLUG) ?? FEATURED[0] ?? COMMISSIONS[0];
  // Prefer a portrait frame. The cover sits in a half-width, full-height
  // column, and `object-cover` on a landscape frame in that shape crops away
  // both sides — usually most of the subject.
  const frame =
    project?.images.find((f) => f.height > f.width) ?? project?.images[0];
  return project && frame ? { project, frame } : null;
})();

/**
 * Which contact-form branch a project should pre-select.
 *
 * The point is that someone who has just looked at a campaign and wants one
 * arrives at the form with "Campaign" already chosen and the usage-rights
 * question already asked. Every question they do not have to answer from a
 * cold start is a chance they do not abandon the form.
 */
export const enquiryTypeFor = (p: Project): string => {
  const slugs = p.categories.map((c) => c.slug);

  if (
    slugs.some((s) =>
      ["artist-presskit", "music-video", "coverart", "events"].includes(s),
    )
  )
    return "music";
  if (slugs.includes("campaigns")) return "campaign";
  if (slugs.includes("editorial")) return "editorial";
  if (p.categories.some((c) => c.section === "SESSIONS")) return "session";
  return "other";
};

/**
 * The project after this one, for the end of a case study.
 *
 * A project page that ends in a footer is a dead end, and a dead end is an
 * exit. Wrapping round at the end means there is always a next thing.
 */
export const nextAfter = (p: Project): Project | undefined => {
  const pool = p.categories.some((c) => c.section === "SESSIONS")
    ? SESSIONS
    : COMMISSIONS;
  const i = pool.findIndex((x) => x.slug === p.slug);
  if (i === -1) return pool[0];
  return pool[(i + 1) % pool.length];
};

/**
 * The disciplines the homepage cycles through, each with a frame to show for
 * it.
 *
 * This is what the cover is *for*: "photographer" is a job title, whereas
 * editorial, campaigns, portraits, artist presskits and cover art are the
 * things somebody might actually be here to commission. Switching between them
 * says the range in the first few seconds, which one static cover cannot.
 *
 * Built from the nav's own category order rather than a hand-written list, so
 * it cannot drift out of step with the work. Each one takes its frame from the
 * first project filed under it — Julian's own ordering, so the lead project is
 * already his pick — preferring a portrait frame, because the cover sits in a
 * tall column and `object-cover` on a landscape frame there crops away both
 * sides.
 */
export type Discipline = {
  slug: string;
  name: string;
  /** How many projects are filed under it, for the index. */
  count: number;
  /** Where the row goes when clicked. */
  href: string;
  /**
   * What the frame on screen is, and where it goes.
   *
   * A project, for every discipline whose frame comes out of the archive.
   * Video's frame can be a film's poster instead, and then the thing to
   * credit is the film — so this is a name and an href rather than a
   * `Project`, and it is optional: a frame nobody can be credited for draws
   * no label, which the cover already handled (`if (!project) return null`)
   * before there was a case that reached it.
   */
  credit?: { name: string; href: string };
  frame: Frame;
};

/**
 * Hand-picked cover frames, overriding the one derived from the archive.
 *
 * These live in `public/hero/` rather than in `public/work/`, because they are
 * chosen to be a cover — a specific frame Julian wants leading the site —
 * rather than being part of a project's sequence. That also keeps them clear
 * of `scripts/harvest.mjs`, which owns everything under `public/work/`.
 *
 * `color` is the mat drawn behind the picture where the column is wider or
 * taller than the frame. It is the image's mean, not its dominant: on a
 * sunset frame the dominant bucket comes back near-black, which reads as a
 * letterbox bar instead of a mount.
 *
 * Add a full-resolution original to `PICS/`, then process it the same way the
 * archive is processed — 2500px wide, mozjpeg q82 — and add an entry here.
 */

/**
 * An override that names a frame already in the archive.
 *
 * Dimensions are read from the manifest rather than written here, because
 * these two entries used to carry their own copy of them and a re-harvest
 * silently invalidated it: raising the archive to 2500px turned every
 * hardcoded `1600` into a lie, and a wrong `width`/`height` on a `fill` image
 * is a wrong aspect ratio reserved before the picture loads — the cover
 * column jumping the moment it arrives.
 *
 * Only `alt` is stated, because that is the one thing the harvest genuinely
 * does not know: 1,084 frames came across with none.
 */
const archiveFrame = (src: string, alt: string): Frame => {
  const found = PROJECTS.flatMap((p) => p.images).find((f) => f.src === src);
  // Naming a frame that does not exist is an editorial mistake, not a runtime
  // condition to paper over — and a silent fallback here would put the wrong
  // photograph at the top of the homepage.
  if (!found)
    throw new Error(`Cover override names a frame not in the archive: ${src}`);
  return { ...found, alt };
};

const COVER_OVERRIDES: Record<string, Frame> = {
  portraits: {
    src: "/hero/cover.jpg",
    width: 2500,
    height: 3333,
    color: "#897A74",
    alt: "Model in a fur-trimmed hooded coat on the shoreline at sunset",
  },
  // Exactly 4:5, so it fills the cover column with nothing cropped at all —
  // the only frame in the archive that does.
  editorial: archiveFrame(
    "/work/i-wanna-be-a-human/01.jpg",
    "Model in a sculptural black PVC and tulle look, flanked by motion-blurred figures",
  ),
  // Already in the archive, so it points there rather than getting a copy in
  // `/hero/` — the override exists to name the frame, and the frame is a
  // UKIYOSUNKNOWN one rather than the first of the first project filed under
  // campaigns, which is what it would otherwise be. The credit follows the
  // frame, via `frameProject` below.
  campaigns: archiveFrame(
    "/work/ukiyosunknown/01.jpg",
    "Model crouched on a studio floor beside a CRT television, looking away from camera",
  ),
  coverart: {
    // The one discipline whose work is not a photograph but a released object,
    // so it is shown as one: sleeves laid out as prints, the lead release
    // square to camera and the rest running off the edges. A single sleeve
    // pulled from the archive says "here is a picture"; the spread says "here
    // is a body of covers", which is the claim the row is making.
    src: "/hero/coverart.jpg",
    width: 2500,
    height: 3125,
    color: "#65696A",
    alt: "Album sleeves laid out as prints, EST MODVS IN REBVS square to camera at the centre",
  },
};

/**
 * The photograph that stands for a category.
 *
 * Shared by the cover's index and the discipline page's header, so the frame
 * a visitor sees for CAMPAIGNS on the homepage is the same one they land on
 * when they click it. Overridden by hand where the derived choice is not the
 * right one, and otherwise the opening frame of whatever project leads the
 * category — Julian's own ordering, so it is already his pick.
 *
 * Prefers a portrait frame: both places put this in a tall column, where
 * `object-cover` on a landscape frame crops away both sides.
 */
export const categoryFrame = (categorySlug: string): Frame | null => {
  // Picked in /admin, and it wins: `COVER_OVERRIDES` below is the default
  // somebody committed by hand, and a choice made in the editor should not
  // lose to one made in code months ago.
  //
  // A path here rather than a whole frame, so the dimensions and mat colour
  // come from the archive — and `?? null` rather than a throw, because
  // `archiveFrame` throwing is right for a typo in code and wrong for a
  // browser form: a frame that has since been removed from a gallery should
  // cost this discipline its picked cover, not the whole build.
  const picked = DISCIPLINE_COVERS[categorySlug];
  if (picked) {
    const found = PROJECTS.flatMap((p) => p.images).find(
      (f) => f.src === picked,
    );
    if (found) return found;
  }

  const override = COVER_OVERRIDES[categorySlug];
  if (override) return override;

  const project = projectsIn(categorySlug)[0];
  if (!project) return null;

  return (
    project.images.find((f) => f.height > f.width) ?? project.images[0] ?? null
  );
};

/**
 * The project a frame belongs to, read off the frame's own path.
 *
 * An override changes which photograph stands for a discipline, but it used to
 * leave the credit pointing at whatever project led the category: the cover
 * showed a UKIYOSUNKNOWN frame under CAMPAIGNS and captioned it "JUBO", which
 * is the first project filed there. Deriving the owner from the path means the
 * caption cannot disagree with the picture — for this override or the next one.
 *
 * Frames outside `/work/<slug>/` — the hand-made ones in `/hero/` — have no
 * project, and the caller falls back to the category's lead.
 */
const frameProject = (frame: Frame): Project | undefined =>
  bySlug.get(frame.src.split("/")[2] ?? "");

/**
 * The disciplines the cover cycles through, in order.
 *
 * Named explicitly rather than taken as the first N categories. The nav order
 * puts `video` fifth, and `video` has no projects at all — which ones lead the
 * site is an editorial call, not something to be decided by a `slice`.
 *
 * A category with no lead project or no frame is dropped below, so this list
 * cannot put an empty discipline on the cover even if one is added to it.
 */
const DEFAULT_DISCIPLINE_SLUGS = [
  "editorial",
  "campaigns",
  "portraits",
  "mixed-media",
  "artist-presskit",
  "coverart",
  // The moving work, added last so the six the cover has always opened with
  // keep their numbers. It carries its own frame rather than one from the
  // archive — see `videoFrame`.
  "video",
];

/**
 * What the cover actually runs through.
 *
 * Curated in /admin now, falling back to the six above when nothing has been
 * chosen — so the homepage is unchanged until somebody decides otherwise, and
 * emptying the list in the editor restores the original rather than producing
 * a cover with no disciplines on it.
 *
 * Which disciplines exist and which the cover shows are two different
 * questions, and this is the second one. Every discipline gets a page and a
 * row in the work index regardless; seven of the thirteen were already on the
 * site without being on the cover before any of this was editable.
 */
const DISCIPLINE_SLUGS = CONTENT.heroDisciplines.length
  ? CONTENT.heroDisciplines
  : DEFAULT_DISCIPLINE_SLUGS;

/**
 * Where the unit of work is not a frame.
 *
 * Cover art is counted in releases: two of them are sleeves with a front and
 * a back, and counting those as two covers each both overstates the work and
 * disagrees with the number the section's own link shows.
 */
const DISCIPLINE_COUNTS: Record<string, number> = {
  coverart: COVER_RELEASES.length,
  // Films, not projects: Video has no projects in the archive at all.
  video: CONTENT.videos.length,
};

/**
 * The cover frame for Video, which has no work in the archive to derive one
 * from.
 *
 * A picked frame first — /admin's Disciplines tab writes one into
 * `DISCIPLINE_COVERS`, and a photograph of his own at full resolution with a
 * real mat colour is the better cover by a distance.
 *
 * Failing that, the first film's own still, so the row works the moment a
 * link is pasted rather than waiting on a second decision. `maxresdefault`
 * and not the default `hqdefault`: 1280x720 against 480x360, and this is the
 * largest paint on the page. The mat is left transparent because a provider
 * still comes with no colour analysis — the section's own ground shows
 * through while it decodes, which is the theme-appropriate answer rather than
 * a guessed one.
 *
 * The loader already handles the remote URL: "an absolute URL is somebody
 * else's and is already complete" (`image-loader.ts`), so it passes through
 * untransformed.
 */
const videoFrame = (): Frame | null => {
  const picked = categoryFrame("video");
  if (picked) return picked;

  const film = CONTENT.videos[0];
  if (!film) return null;

  const still =
    film.poster ??
    (film.provider === "youtube"
      ? `https://i.ytimg.com/vi/${film.videoId}/maxresdefault.jpg`
      : null);
  if (!still) return null;

  return { src: still, width: 1280, height: 720, color: "transparent", alt: `${film.title} — a film by Julian Gigola` };
};

export const DISCIPLINES: Discipline[] = DISCIPLINE_SLUGS.map((slug) =>
  CATEGORIES.find((c) => c.slug === slug),
)
  .filter((c): c is Category => Boolean(c))
  .map((category) => {
    const inCategory = projectsIn(category.slug);
    const lead = inCategory[0];

    /* Video is the one discipline with no work in the archive: its films live
       on YouTube and Vimeo and its frame comes from `videoFrame`. So the
       "no lead project" test cannot be the gate for it — what gates it is
       having a film at all, which is the same rule the work index applies to
       its chip. */
    const isVideo = category.slug === "video";
    if (!lead && !isVideo) return null;
    if (isVideo && CONTENT.videos.length === 0) return null;

    const frame = isVideo ? videoFrame() : categoryFrame(category.slug);
    if (!frame) return null;

    // Whatever the frame actually came from, so the cover's credit names the
    // picture on screen. Only differs from the lead where an override has
    // reached into another project for the frame.
    const project = frameProject(frame) ?? lead;

    // Some nav leaves are a listing of many projects (EDITORIAL); others are
    // themselves a single gallery (COVERART, WEDDINGS). Counting projects for
    // the second kind always reports "1", which is true and useless — the
    // number a visitor wants is how much work is in there.
    const count =
      DISCIPLINE_COUNTS[category.slug] ??
      // `lead`, not `project`: where the category *is* a gallery, the number
      // is that gallery's size — not the size of whatever project an override
      // happened to borrow a frame from.
      (isOwnGallery(category.slug) ? lead!.images.length : inCategory.length);

    /* Credit the thing on screen. A photograph credits its project; a film's
       poster credits the film, and goes to the page it plays on. */
    const credit = project
      ? { name: project.name, href: `/work/${project.slug}` }
      : isVideo && CONTENT.videos[0]
        ? { name: CONTENT.videos[0].title, href: "/work/video" }
        : undefined;

    return {
      slug: category.slug,
      name: categoryLabel(category),
      count,
      href: categoryHref(category.slug),
      // Spread rather than assigned: `credit?:` means absent, and `strict`
      // will not take `undefined` for it.
      ...(credit ? { credit } : {}),
      frame,
    };
  })
  .filter((d): d is Discipline => d !== null);

/**
 * The cover-art work.
 *
 * It sits apart from the rest of the archive because its format does: every
 * frame is exactly 1:1, because that is what a release needs. Shown in a
 * square grid rather than folded into the portrait-shaped selected-work grid,
 * where squares would have to be cropped to fit.
 */
export const COVER_ART: Project | undefined = getProject("coverart");
