/**
 * The shape of the work manifest.
 *
 * Kept separate from `work.ts` because that file is generated — the harvester
 * overwrites it, and a hand-written type would go with it.
 */

/**
 * The old site's three nav groups. Kept because they encode something real —
 * who the work is *for* — even though the new nav collapses MUSIC into Work
 * and gives Sessions its own path.
 */
export type Section = "WORK" | "SESSIONS" | "MUSIC";

export type Category = {
  /** Route segment, matching the old site so inbound links keep working. */
  slug: string;
  /** As it reads in the nav. Uppercase on the old site. */
  name: string;
  /** Null for a category the old nav never linked. */
  section: Section | null;
};

export type Frame = {
  /** Path under `public/`. */
  src: string;
  width: number;
  height: number;
  /**
   * The image's dominant colour, from Format's own analysis. Used as the
   * placeholder behind a frame while it decodes, which reads better than a
   * grey box: the page settles *into* the photograph rather than replacing a
   * different colour with it.
   */
  color: string;
  /** Empty on most frames — the old site never filled these in. */
  alt: string;
  /**
   * A 16px copy inlined as a data URL, painted under the picture while it
   * loads. Only covers have one (`scripts/make-cards.mjs`), attached where
   * a list is built for a client component so only the ones a page shows
   * travel with it.
   */
  blur?: string;
};

export type Credit = {
  /** "Photographer", "Client", "Styling"… */
  role: string;
  name: string;
  /**
   * Their Instagram, as a bare handle — no `@`, no URL.
   *
   * Optional because the seventy harvested projects have none: the old site
   * credited by name only, and `lib/work-data.ts` is regenerated by
   * `scripts/harvest.mjs`, so anything added here by hand would be wiped by
   * the next run. Handles are added through `/admin`, which stores them in
   * `content/projects.json` as an override the harvest cannot touch.
   */
  instagram?: string | null;
  /**
   * The handle this credit actually links to, worked out once in
   * `lib/work.ts`: `instagram` when there is one, and otherwise the name
   * itself where the old site wrote the credit as "@apricotsss3".
   */
  handle?: string | null;
  /**
   * Their profile photograph, a path under `public/`, when one has been
   * saved. Derived from `handle`; see `avatarFor` in `lib/work.ts`.
   */
  avatar?: string | null;
};

/**
 * A passage of writing set into a gallery, between the photographs.
 *
 * Positioned rather than free-floating: `after` is how many frames precede
 * it, so `0` opens the sequence and `images.length` closes it. The number is
 * derived in `lib/work.ts` from where the block sat in the edited sequence —
 * `/admin` stores one list of photographs and text together, because moving a
 * paragraph three frames later is the same gesture as moving a photograph,
 * and asking for a separate index field would be asking Julian to count.
 */
export type TextBlock = {
  /** Optional — a block is often a caption with no title over it. */
  heading: string | null;
  body: string;
  /** How many frames come before it. */
  after: number;
};

/**
 * A project's words, rewritten in /admin: the title on the page and the
 * paragraph under the meta row. Both replace outright; `intent: null`
 * means "publish no paragraph".
 */
export type Copy = { title: string; intent: string | null };

export type Project = {
  slug: string;
  /**
   * The slug it was harvested or added under, when `slug` is no longer
   * that. Set by `reslug` in `lib/work.ts` from the `slugs` map in
   * `content/projects.json`, and read by `next.config.ts` to keep the old
   * address answering. Absent on a project that has never been renamed.
   */
  origin?: string;
  name: string;
  /** The heading from the old title block, where it differs from `name`. */
  headline: string | null;
  /** Prose left over after the credits were parsed out. Usually null. */
  intent: string | null;
  credits: Credit[];
  /**
   * Writing set between the frames, in `after` order.
   *
   * Optional because `lib/work-data.ts` is generated and does not write it,
   * and because it is genuinely absent on almost every project — only a
   * gallery somebody has added a passage to has any. Read it as
   * `blocks ?? []`.
   */
  blocks?: TextBlock[];
  /** Every category this project is listed under, old-site order. */
  categories: Category[];
  /**
   * A 600px copy of the opening frame. The corridor and the work index show
   * dozens of frames at once and none of them large; pointing those at the
   * full-size originals costs megabytes before anything is visible.
   */
  cover: Frame;
  images: Frame[];
};
