/**
 * Client logos, inlined from `public/clients/`.
 *
 * Drop `<slug>.svg` in there — the slug being the project's, so `wired.svg`
 * for WIRED, `oakley-x-nike.svg`, `jubo.svg` — and run this. The band under
 * the cover and the list on /studio draw the mark instead of the name.
 *
 * Inlined into a module rather than served as files, for the same reason
 * every other icon on this site is drawn in the markup: a mark in an `<img>`
 * is a fixed colour, and this one has to sit muted in a row, come up to full
 * contrast on hover, and work on both a near-black and a near-white ground.
 * `currentColor` does all three and an `<img>` does none of them — a black
 * logo is invisible on the dark theme, which is the default here.
 *
 * So every colour in the file is replaced by `currentColor`. That means the
 * source has to be a single-colour SVG: a two-tone mark comes out flat, and
 * a mark whose whole point is its colours belongs in an `<img>` and a
 * different design.
 *
 * Generated and committed, like `work-data.ts` and `cover-art-data.ts` — the
 * logos change when a client is added, which is not a build-time concern.
 *
 *   node scripts/make-clients.mjs
 */

import { readdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const from = join(root, "public/clients");
const to = join(root, "lib/clients-data.ts");

const files = existsSync(from)
  ? readdirSync(from).filter((f) => f.endsWith(".svg"))
  : [];

/**
 * The inside of an SVG, with every colour handed to `currentColor`.
 *
 * Deliberately narrow: attributes and one-line style declarations. A mark
 * with a `<style>` block, a gradient or an embedded raster is refused rather
 * than half-converted — it would render, wrongly, and the failure would show
 * up as one logo that ignores hover.
 */
function inline(svg, name) {
  const viewBox = svg.match(/viewBox="([^"]+)"/i)?.[1];
  if (!viewBox) throw new Error(`${name}: no viewBox — cannot scale it safely`);

  if (/<(style|linearGradient|radialGradient|image)\b/i.test(svg))
    throw new Error(
      `${name}: has a style block, gradient or raster. Flatten it to paths in one colour first.`,
    );

  /* An SVG is a document and may carry script — a `<script>` element, or an
     `onload` on any node. This markup is injected with
     `dangerouslySetInnerHTML`, and the site's CSP allows inline script
     (Next's hydration payload needs it), so such a script would run.

     Refused rather than stripped. A logo has no reason to contain either, so
     a file that does is either broken or not a logo, and quietly removing
     part of it would publish a mark nobody had looked at. */
  if (/<script\b/i.test(svg) || /\son[a-z]+\s*=/i.test(svg))
    throw new Error(
      `${name}: contains script or an event handler. A logo needs neither — export it again as plain paths.`,
    );

  /* Same reasoning for anything reaching outside the file: a mark that loads
     from a URL can be changed by somebody else, and `foreignObject` is a hole
     straight back into HTML. */
  if (/<foreignObject\b/i.test(svg) || /<use\b[^>]*href="(?!#)/i.test(svg))
    throw new Error(
      `${name}: references something outside the file. Flatten it first.`,
    );

  const body = svg
    // Everything between the outer <svg> tags.
    .replace(/^[\s\S]*?<svg[^>]*>/i, "")
    .replace(/<\/svg>[\s\S]*$/i, "")
    // Comments and editor metadata.
    .replace(/<!--[\s\S]*?-->/g, "")
    .replace(/<(title|desc|metadata)\b[\s\S]*?<\/\1>/gi, "")
    // Colours, in attributes and in inline styles.
    .replace(/(fill|stroke)="(?!none\b)[^"]*"/gi, '$1="currentColor"')
    .replace(/(fill|stroke):\s*(?!none\b)[^;"']+/gi, "$1:currentColor")
    .replace(/\s+/g, " ")
    .trim();

  if (!body) throw new Error(`${name}: nothing inside the svg`);
  return { viewBox, body };
}

const marks = {};
for (const file of files) {
  const slug = file.replace(/\.svg$/, "");
  marks[slug] = inline(readFileSync(join(from, file), "utf8"), file);
}

const entries = Object.entries(marks)
  .map(
    ([slug, m]) =>
      `  ${JSON.stringify(slug)}: {\n    viewBox: ${JSON.stringify(m.viewBox)},\n    body: ${JSON.stringify(m.body)},\n  },`,
  )
  .join("\n");

writeFileSync(
  to,
  `/* Generated by \`scripts/make-clients.mjs\` from \`public/clients/*.svg\`.
 * Do not edit: add or replace an SVG and run the script.
 *
 * Every colour is \`currentColor\`, so a mark sits muted in the row, comes up
 * to full contrast on hover, and works on either theme. See the script for
 * why these are inlined rather than served as files.
 */

/** One client's mark, ready to drop into an \`<svg>\`. */
export type ClientMark = { viewBox: string; body: string };

/** By slug — the same slug the project has. Empty until a logo is added. */
export const CLIENT_MARKS: Record<string, ClientMark> = {
${entries}
};
`,
);

console.log(
  files.length
    ? `${files.length} logo${files.length === 1 ? "" : "s"} inlined: ${Object.keys(marks).join(", ")}`
    : "no logos in public/clients yet — every client keeps its wordmark",
);
